name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  JCPP_LOG_LEVEL: debug
  JCPP_LOG_CONSOLE: enable

jobs:
  package-source-tar-gz:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.tar.gz
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}.tar.gz

  package-source-zip:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.zip
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}.zip

  build-linux-x86_64:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz

  build-linux-x86_64-test:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz

  build-linux-x86_64-repo:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.repo.tar.gz

  build-macos-x86_64:
    runs-on: macos-15-intel

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz

  build-macos-x86_64-test:
    runs-on: macos-15-intel

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz

  build-macos-x86_64-repo:
    runs-on: macos-15-intel

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.repo.tar.gz

  build-macos-aarch64:
    runs-on: macos-26

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz

  build-macos-aarch64-test:
    runs-on: macos-26

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz

  build-macos-aarch64-repo:
    runs-on: macos-26

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.repo.tar.gz

  build-windows-x86_64:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip

  build-windows-x86_64-test:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip

  build-windows-x86_64-repo:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.repo.zip

  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz

  build-linux-aarch64-test:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz

  build-linux-aarch64-repo:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.repo.tar.gz

  build-windows-aarch64:
    runs-on: windows-11-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip

  build-windows-aarch64-test:
    runs-on: windows-11-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.test
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip

  build-windows-aarch64-repo:
    runs-on: windows-11-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.repo
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.repo.zip
