name: Build on windows-2025

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJ=5 -DBUILD_TEST=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-source
        path: ${{github.workspace}}/libjdk-17.35.zip

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk
        path: ${{github.workspace}}/libjdk-windows-17.35.zip

  build-withtest:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-withtest
        path: ${{github.workspace}}/libjdk-windows-17.35.zip

  build-repo:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJ=5 -DINSTAll_TO_REPO=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-source
        path: ${{github.workspace}}/libjdk-17.35.tar.gz

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk
        path: ${{github.workspace}}/libjdk-windows-17.35-repo.tar.gz
