name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      configure-arguments:
        description: 'configure arguments'
        required: false
        default: ''
      make-arguments:
        description: 'make arguments'
        required: false
        default: ''

env:
  GENERATOR: Ninja
  CONFIG_ARGS: -S ${{github.workspace}}/src -B ${{github.workspace}}/build ${{github.event.inputs.make-arguments}} -DJ=8
  BUILD_ARGS: --build ${{github.workspace}}/build ${{github.event.inputs.make-arguments}} -v -j 2

jobs:
  package-source-tar-gz:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.tar.gz
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}.tar.gz

  package-source-zip:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.zip
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}.zip

  build-linux-x86_64:
    runs-on: ubuntu-22.04
#    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - name: Install 3rd
      run: |
        sudo apt update
        sudo apt install -y libfontconfig-dev libxrandr-dev libfreetype6-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libasound2-dev libffi-dev

    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz

  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install 3rd
      run: |
        sudo apt update
        sudo apt install -y libfontconfig-dev libxrandr-dev libfreetype6-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libasound2-dev libffi-dev

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz

  build-macos-x86_64:
    runs-on: macos-14-large

    steps:
    - name: Install libffi
      run: brew install libffi

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz

  build-macos-aarch64:
    runs-on: macos-14

    steps:
    - name: Install libffi
      run: brew install libffi

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz

  build-windows-x86_64:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure build
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip

  build-windows-aarch64:
    runs-on: windows-11-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure build
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64

    - name: Configure CMake
      run: cmake ${{env.CONFIG_ARGS}} -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Build
      run: cmake ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64
        path: ${{github.workspace}}/libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip

  release:
    needs: [package-source-tar-gz,package-source-zip,build-linux-x86_64,build-linux-aarch64,build-macos-x86_64,build-macos-aarch64,build-windows-x86_64,build-windows-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.tar.gz
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-source.zip
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          libjdk-${{steps.get-version-id.outputs.id}}.tar.gz
          libjdk-${{steps.get-version-id.outputs.id}}.zip
          libjdk-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz
          libjdk-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz
          libjdk-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz
          libjdk-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz
          libjdk-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip
          libjdk-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip